import type { GeneratedPlaybook } from "./recommendation-prompt";

/**
 * Formats the playbook as clean structured text suitable for pasting into
 * NotebookLM, Claude, ChatGPT, or any AI tool as context.
 */
export function generatePlaybookText(playbook: GeneratedPlaybook): string {
  const lines: string[] = [
    `# CX Playbook — ${playbook.companyName}`,
    `Generated by CX Mate`,
    "",
  ];

  // Week one checklist
  if (playbook.weekOneChecklist?.length) {
    lines.push("## Start This Week");
    playbook.weekOneChecklist.forEach((item, i) => {
      lines.push(`${i + 1}. ${item}`);
    });
    lines.push("");
  }

  // Quick wins
  if (playbook.quickWins?.length) {
    lines.push("## Quick Wins (Highest Impact, Lowest Effort)");
    playbook.quickWins.forEach((rec) => {
      lines.push(`- ${rec.action} (${rec.owner}, ${rec.timing})`);
    });
    lines.push("");
  }

  // Stage playbooks
  playbook.stagePlaybooks?.forEach((stage) => {
    lines.push(`## ${stage.stageName}`);
    if (stage.topPriority) lines.push(`Top priority: ${stage.topPriority}`);
    if (stage.measurementPlan) lines.push(`Measure: ${stage.measurementPlan}`);
    lines.push("");

    stage.recommendations?.forEach((rec) => {
      lines.push(`### ${rec.action}`);
      lines.push(`- Priority: ${rec.priority}`);
      lines.push(`- Owner: ${rec.owner}`);
      lines.push(`- Timing: ${rec.timing}`);
      lines.push(`- Effort: ${rec.effort}`);
      if (rec.toolsUsed?.length) lines.push(`- Tools: ${rec.toolsUsed.join(", ")}`);
      if (rec.template) {
        lines.push(`- Template:`);
        lines.push(rec.template);
      }
      lines.push(`- Expected outcome: ${rec.expectedOutcome}`);
      lines.push(`- Measure with: ${rec.measureWith}`);
      lines.push("");
    });
  });

  return lines.join("\n");
}
